### ISSUE TITLE
Pre-trained Model 

### ISSUE THREAD

**Issue by litong123** [ncarraz/AFILM#1]
Thanks for your work, but can you provide a pre-trained model or trained parameters?

**Comment by ncarraz** [comment]
I plan to release pretrained models soon.

**Comment by litong123** [comment]
Thanks. I will look forward to the release of the pre-trained models.

**Comment by Coice** [comment]
@ncarraz any updates on the pre-trained model? I am currently unable to train and would love to hear your results. Many thanks in advance!

**Comment by ncarraz** [comment]
I just uploaded some models from the paper. There are more to come.
