### ISSUE TITLE
Questions about model input size and output size

### ISSUE THREAD

**Issue by bnbn860904** [ncarraz/AFILM#5]
Dear ncarraz

I'm currently learning about Audio Super Resolution.
I want to ask you a question.
Why does the output of the model have a length of 8192 instead of double, four or eight times the length of the input ?
According to my understanding, to increase the resolution, the length of the output should be longer.

If you can answer me I will thank you very much.
thanks.

**Comment by ncarraz** [comment]
Hello, 
The number 8192 I am referring in the paper is the input patch length. 
The output length depends on the input and the scaling factor.

**Comment by bnbn860904** [comment]
Got it, thanks for your quick reply.
