### ISSUE TITLE
Pretrained model disappear

### ISSUE THREAD

**Issue by yxlu-0102** [ncarraz/AFILM#6]
I can't find the pre-trained model through the link you provided, can you check it out and re-upload them?

**Comment by ncarraz** [comment]
Unfortunately, the account associated with the google drive containing the model files has been deleted. We will re-train the models and re-upload them by the end of the year.

**Comment by yxlu-0102** [comment]
I installed tensorflow-gpu=2.6.0 and keras=2.6.0 and ran in to this problem `AttributeError: 'MaxPooling1D' object has no attribute '_metrics_lock'`.

**Comment by ncarraz** [comment]
I recovered these files: VCTK-scale_2-Multi: https://drive.google.com/file/d/1F9WCHI-muWYQy2n1MpgAEtGKSIRUe3Go/view?usp=share_link, VCTK-scale_4-Multi: https://drive.google.com/file/d/1-5JfveMwPWS-3C2V8pJx7QJ4PzG24N55/view?usp=share_link

**Comment by yxlu-0102** [comment]
Thanks a million!

**Comment by yxlu-0102** [comment]
If I want to train your model, how many epochs should I set? I find the results of 20 epochs seems not that good.

**Comment by yxlu-0102** [comment]
> I recovered these files: VCTK-scale_2-Multi: https://drive.google.com/file/d/1F9WCHI-muWYQy2n1MpgAEtGKSIRUe3Go/view?usp=share_link, VCTK-scale_4-Multi: https://drive.google.com/file/d/1-5JfveMwPWS-3C2V8pJx7QJ4PzG24N55/view?usp=share_link

I found the spectrogram of the waveforms generated from the ckpt you provided have something run, this is because the [audio-super-res](https://github.com/kuleshov/audio-super-res) use `x_lr = np.array(x_hr[0::args.r])` instead of `x_lr = decimate(x_hr, args.r)` to downsample the x_hr by default, you should point it out in your `test.py`.

**Comment by ncarraz** [comment]
The models were trained for 50 epochs. Thank you for pointing it out.
